return PlaceObj('ModDef', {
	'title', "[Beta] Super Big Map",
	'description', "Beta testing version: bugs will occur. Please test and report.\n\n[BUG] Apparently it gets stuck at loading in the PS5 version. I need a tester so that I can fix that.\n\n------------------------------------------------------------\n\nSuper Big Map\n\n3x more map. No extra fries.\n\nOn the Colony Site screen, toggle EXPAND MAP before pressing START to expand that new game from a 10 x 10 sector grid to a 20 x 20 sector grid, giving you 300 additional sectors to explore and build on.\n\nLeave EXPAND MAP off to start normally with vanilla map size and vanilla zoom. ZoomPlus is only enabled on maps actually expanded by this mod. Expanded-map zoom can be changed in Game Options -> Options -> Display -> Max Zoom Level.\n\nRequirements and Compatibility:\n\nYou must start a new game with EXPAND MAP toggled on. Existing saves will not be expanded.\nInitial loading takes longer because the expanded map requires more processing.\nDo not use other zoom mods. SBM includes its own zoom settings for expanded maps.\n------------------------------------------------------------\n\n[IMPORTANT]: Quit and restart the game after enabling this mod to clear cached data.\nTested only on Surviving Mars Relaunched v1.0.7 on Windows 11.\nPlease complain! I can’t fix what I don’t know is broken. Anonymous feedback: https://smr-mods-feedback.fredware.app or github: https://github.com/facazevedo/surviving-mars-relaunched-mods/issues",
	'short_description', "Adds an opt-in EXPAND MAP start toggle for 20 x 20 maps.",
	'image', "Mod/SuperBigMap/Images/final_composed.jpg",
	'last_changes', "Expanded maps now get resources, anomalies and research sites at full VANILLA DENSITY for the larger size (deposits topped up and anomaly counts scaled by the area factor, then spread evenly -- landing spot no longer over-crowded). Also: non-expanded maps keep the exact vanilla overview, and the EXPAND MAP button no longer disappears after returning to the colony-site screen.",
	'id', "SuperBigMap",
	'author', "fredware",
	'version', 339,
	'lua_revision', 350453,
	'saved_with_revision', 396349,
	'code', {
		"Code/sbm_version.lua",
		"Code/sbm_config.lua",
		"Code/sbm_debug.lua",
		"Code/sbm_engine.lua",
		"Code/sbm_pregame_toggle.lua",
		"Code/ZoomPlus.lua",
		"Code/sbm_overview_camera.lua",
		"Code/sbm_overview_curtains.lua",
		"Code/sbm_overview_render.lua",
		"Code/sbm_zoomplus_integration.lua",
		"Code/sbm_zoom_option.lua",
		"Code/sbm_sector_grid.lua",
		"Code/sbm_map_bounds.lua",
		"Code/sbm_sector_exploration.lua",
		"Code/sbm_sector_highlight.lua",
		"Code/sbm_object_clone.lua",
		"Code/sbm_terrain_copy.lua",
		"Code/sbm_rmg_placement.lua",
		"Code/sbm_map_generation.lua",
		"Code/sbm_seam_blend.lua",
		"Code/sbm_seam_tuner.lua",
		"Code/sbm_scan_all_button.lua",
		"Code/sbm_deposits.lua",
		"Code/sbm_fake_terrain.lua",
		"Code/sbm_rocket_rules.lua",
		"Code/sbm_heat_safety.lua",
		"Code/sbm_validation.lua",
		"Code/sbm_loading_ui.lua",
		"Code/sbm_lifecycle.lua",
		"Code/SuperBigMap.lua",
	},
	'saved', 1783435542,
	'code_hash', -1524056503762230759,
	'pdx_id', 146312,
	'pdx_version', "3",
	'steam_id', "3759751183",
	'TagGameplay', true,
})
